# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM nvcr.io/nvidia/pytorch:24.09-py3

ENV APP_HOME=/app
WORKDIR $APP_HOME

# Install production dependencies.
COPY requirements.txt ./
RUN pip install --no-cache-dir -r ./requirements.txt

# Copy local code to container image
COPY kserve_model.py ./

CMD ["python", "kserve_model.py"]